config/routes.rb
Rails.application.routes.draw do

devise_for :admins, controllers: { sessions: 'admins/sessions' }

devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}

  namespace :admins do
     resources :users, only: [:show, :index, :destroy]
     resources :jenres, only: [:index, :edit, :create, :update]
     resources :top_admin, only: [:index]
  end

  root 'homes#top'
  get 'homes/top'

  get 'users/passwords/:id', to:"users#passwords", as: :passwords
  patch '/users/passwords/:id' ,to: "users#pass_update"
  put   '/users/passwords/:id' ,to: "users#pass_update"
  get 'users/withdraw/:id' => 'users#withdraw', as: :withdraw
  resources :users, only: [:show, :edit, :update, :destroy] do
    post 'follow/:id' => 'relationships#follow', as: 'follow'
    post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end

  resources :styles, only: [:index, :show, :new, :edit, :create, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
  end

  resources :boards, only: [:show, :index, :create, :destroy] do
    resource :board_comments, only: [:create, :destroy]
  end

  resources :chats, only: [:create]
  resources :rooms, only: [:create, :show]

  resources :salons, only: [:create, :destroy, :new, :edit, :update]

  resources :contacts, only: [:create]

  get 'tags/:tag', to: 'styles#index', as: :tag

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # 登録メール機能
  after_create :send_welcome_mail

  # 論理削除
  acts_as_paranoid

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :salons, dependent: :destroy
  has_many :styles, dependent: :destroy
  has_many :boards, dependent: :destroy
  has_many :board_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorites_styles, through: :favorites, source: :style
  has_many :chats, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  has_many :rooms, through: :user_rooms

  attachment :profile_image

  validates :name, presence: true, length: 2..20
  # user名前２から20文字いない
  validates :kana_name, presence: true, length: 2..20
  validates :nickname, presence: true, length: 2..20
  validates :prefectures, presence: true, length: 2..5
  validates :body, length: {maximum: 100}
  # プロフィール文50文字いない
  validates :email, presence: true

  enum status: { 一般: 0, 美容師: 1 }


  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # フォロワー取得
  has_many :following_user, through: :follower, source: :followed
  # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower
  # 自分をフォローしている人

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end

  # ユーザ登録後にメールを送信する処理
  def send_welcome_mail
    UserMailer.user_welcome_mail(self).deliver
  end

  def self.search(search)
      where(['nickname LIKE ?', "%#{search}%"])
  end

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :authenticate_admin!

  layout 'admins'

  def show
  	@user = User.find(params[:id])
  end

  def index
  	if params[:search]
  	  @users = User.without_deleted.search(params[:search])
  	else
  	  @users = User.without_deleted
  	 end
  	@user_deletes = User.only_deleted
  end

  def destroy
  	@user = User.find(params[:id])
  	@user.destroy
  	flash[:notice] = "会員を削除しました"
  	redirect_to admins_users_path
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :kana_name, :nickname, :prefectures, :status, :email])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  layout 'styletops'

  def show
    @user = User.find(params[:id])
    @user_salons = @user.salons
    @user_styles = @user.styles
    # チャット機能
    @currentUserEntry = UserRoom.where(user_id: current_user.id)
    @userEntry = UserRoom.where(user_id: @user.id)

    # 自分のルーム一覧
    targetRoomIdList = UserRoom.select(:room_id).where(user_id: @user.id)
    @rooms = Room.where(id: targetRoomIdList)

    # サイドバー
    @jenres = Jenre.all
    @tags = ActsAsTaggableOn::Tag.all
    @boards_new = Board.limit(5).order("created_at desc")
    @styels_new = Style.limit(12).order("created_at desc")

    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isroom = true
            @roomid = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = UserRoom.new
      end
    end
  end

  def edit
    @user = User.find(params[:id])

    # サイドバー
    @jenres = Jenre.all
    @tags = ActsAsTaggableOn::Tag.all
    @boards_new = Board.limit(5).order("created_at desc")
    @styels_new = Style.limit(12).order("created_at desc")

    if current_user != @user
      redirect_back(fallback_location: root_path)
    end
  end

  def withdraw
    @user = User.find(params[:id])
  end

  def passwords
    @user = User.find(params[:id])
  end

  def pass_update
    @user = User.find(params[:id])
    if @user.update(password_params)
      flash[:notice] = "パスワードを変更しました"
      redirect_to root_path
    else
      render :passwords
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "会員情報を変更しました"
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private

    def user_params
      params.require(:user).permit(:name, :kana_name, :nickname, :prefectures, :status, :profile_image, :email, :body)
    end

    def password_params
      params.require(:user).permit(:password, :password_confirmation)
    end

end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="row">
  <div class="col-xs-2 index-status">
    <%= render 'layouts/sidebar', jenres: @jenres, tags: @tags, boards_new: @boards_new, styels_new: @styels_new %>
  </div>

  <div class="col-xs-10">
    <div class="col-xs-12 text-center">
	    <h2 class="main-tex"><strong>My Page 編集</strong></h2>
    </div>

    <%= form_for @user do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="row">
        <div class="col-xs-6 text-center">
          <%= attachment_image_tag @user, :profile_image, :fill, 250, 300, fallback: "no_image.jpg", id: :img_prev, class: "profile-image pre" %><br>
          <%= f.attachment_field :profile_image, class: "btn btn-danger image-tag", id: :user_img %>
        </div>
        <div class="col-xs-4">

          <label class="col-sm-12 text-user">氏名</label>
          <div class="col-sm-12"><%= f.text_field :name, class: "my-edit" %></div>

          <label class="col-sm-12 text-user">フリガナ</label>
          <div class="col-sm-12"><%= f.text_field :kana_name, class: "my-edit" %></div>

          <label class="col-sm-12 text-user">ニックネーム</label>
          <div class="col-sm-12"><%= f.text_field :nickname, class: "my-edit" %></div>

          <label class="col-sm-12 text-user">PR(100文字以内)</label>
          <div class="col-sm-12"><%= f.text_area :body, class: "my-edit" %></div>

          <label class="col-sm-12 text-user">都道府県</label>
          <div class="col-sm-12"><%= f.text_field :prefectures, class: "my-edit" %></div>

          <label class="col-sm-12 text-user">メールアドレス</label>
          <div class="col-sm-12"><%= f.text_field :email, class: "my-edit" %></div>

          <label class="col-sm-12 text-user">情報(一般or美容師)</label>
          <div class="col-sm-12"><%= f.select :status, ['一般', '美容師'] %></div>

          <div class="col-sm-12">
            <%= f.submit "変更を保存", class: "btn btn-danger image-tag" %>
            <%= link_to 'パスワード変更', passwords_path(@user.id), class: "btn btn-danger image-tag" %>
            <%= link_to '退会する', withdraw_path, class: "btn btn-danger image-tag" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/passwords.html.erb
<div class="row main-back">
  <div class="col-xs-12 text-center bottom-set">
    <h2>パスワード再設定フォーム</h2>
    <%= form_for(@user, url: passwords_path) do |f| %>
      <div class="field botton-b">
        <%= f.label :password, "パスワード(6文字以上)" %><br />
        <% if @minimum_password_length %>
          <em>(<%= @minimum_password_length %> 文字以上入力して下さい)</em>
        <% end %><br />
        <%= f.password_field :password, autocomplete: "new-password", size: "50", class: "text-pas" %>
      </div>

      <div class="field botton-b">
        <%= f.label :password_confirmation, "パスワード(確認用)" %><br />
        <%= f.password_field :password_confirmation, autocomplete: "new-password", size: "50", class: "text-pas" %>
      </div>

      <div class="actions">
        <%= f.submit "変更する", class: "btn btn-danger botton-d" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-xs-2 index-status">
    <%= render 'layouts/sidebar', jenres: @jenres, tags: @tags, boards_new: @boards_new, styels_new: @styels_new %>
  </div>
  <!-- User詳細ページ -->
  <div class="col-xs-10">
    <div class="col-xs-12 style-main-visual">
      <div class="col-xs-12 text-center">
        <% if @user.status == "美容師" %>
          <h2 class="main-tex"><strong>Stylist Page</strong></h2>
        <% elsif @user == current_user %>
	        <h2 class="main-tex"><strong>My Page</strong></h2>
        <% else %>
          <h2 class="main-tex"><strong>User Page</strong></h2>
        <% end %>
      </div>

      <!-- my情報 -->
      <div class="col-xs-6 text-center">
        <%= attachment_image_tag @user, :profile_image, :fill, 300, 360, fallback: "no_image.jpg", class: "profile-image-white" %>
        <div class="col-xs-12 text-center follow-botton">
          <%= render 'relationships/follow', user: @user %>
        </div>
        <div class="col-xs-12">
          <div class="col-xs-2">
          </div>
          <div class="col-sm-8 text-user my-top-main-follow text-center">
      フォロー中 : <%= link_to @user.follower.count, user_follows_path(@user.id), class: "follow-color" %> | フォロワー : <%= link_to @user.followed.count, user_followers_path(@user.id), class: "follow-color" %>
          </div>
        </div>
        <div class="col-xs-12 text-center index-top">
          <% unless @user == current_user %>
            <div class="row">
              <% if @isroom == true %>
                <%= link_to "チャットへ", room_path(@roomid), class: "btn btn-warning chat" %>
              <% else %>
                <%= form_for @room do |room| %>
                  <%= fields_for @entry do |e| %>
                    <%= e.hidden_field :user_id, :value=> @user.id %>
                  <% end %>
                    <%= room.submit "チャットを始める", class: "btn btn-warning chat" %>
                <% end %>
             <% end %>
            </div>
          <% end %>
        </div>
        <% if @user == current_user %>
          <div class="col-xs-12 text-center">
            <div class="col-xs-2">
            </div>
            <div class="col-xs-8 rooms-user">
              <% @rooms.each do |room| %>
                <div class="room-users text-center">
                  <%= link_to room_path(room.id), class: "room-users-text" do %>
                    <%= room.id %>
                    チャット件数 : <%= room.chats.count %> 件<br>
                    <% room.user_rooms.each do |user| %>
                      <%= user.user.nickname %>
                    <% end %>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="col-xs-6">
        <label class="col-sm-10 text-user my-top-main"><%= @user.nickname %> | <%=@user.status %></label>
        <label class="col-sm-10 my-top"><%= @user.body %></label>
        <% if @user == current_user %>
          <label class="col-sm-10 my-top"><%= @user.name %> | <%= @user.kana_name %></label>
          <label class="col-sm-10 my-top"><%= @user.prefectures %></label>
          <label class="col-sm-10 my-top"><%= @user.email %></label>
        <% end %>
        <!-- サロン情報 -->
        <% if @user.status == "美容師" %>
          <div class="col-xs-10">
            <div class="row">
              <div class="col-xs-12 text-center">
                <h2 class="main-tex2"><strong>Salon</strong></h2>
              </div>
            </div>
            <div class="row salon-box">
              <div class="col-xs-10 text-center dis">
                <% @user_salons.each do |f| %>
                  <div class="card it" style="width: 30rem;">
                    <figure class="effect-scale">
                      <%= attachment_image_tag f, :salon_image, :fill, 260, 220, format: 'jpeg', class: "card-img-top ima" %>
                    </figure>
                    <div class="card-body">
                      <p class="card-text"><strong><%= f.salon_name %></strong></p>
                      <p class="card-text"><strong><%= f.salon_address %></strong></p>
                      <p class="card-text"><strong><%= f.salon_phone %></strong></p>
                      <% if @user == current_user %>
                        <%= link_to 'Salon編集', edit_salon_path(f.id), class: "botton-salon btn-sm btn-danger" %>
                        <%= link_to "Salon削除",salon_path(f.id), class: "botton-salon btn-sm btn-danger", method: :delete,"data-confirm" => "本当に削除しますか?" %>
                      <% end %>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
            <% if @user == current_user %>
              <div class="row text-center">
                <%= link_to 'Salon新規登録', new_salon_path, class: "botton-date btn btn-danger" %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
      <% if @user == current_user %>
        <div class="row text-center">
          <%= link_to 'マイページ編集', edit_user_path, class: "botton-date btn btn-danger" %>
        </div>
      <% end %>
    </div>


    <% if @user.status == "美容師" %>

      <!-- myスタイル一覧 -->
      <div class="col-xs-12 style-main-visual">
        <div class="row">
          <div class="col-xs-12 text-center">
            <h2 class="main-tex"><strong><%= @user.nickname %> HearStyles</strong></h2>
          </div>
        </div>
        <div class="row">
          <div class="my-styles-user">
            <div class="col-xs-12">
              <% @user_styles.each do |f| %>
                <div class="box box-efect">
                  <%= link_to style_path(f.id) do %>
                    <%= attachment_image_tag f, :image, :fill, 200, 250, format: 'jpeg', class: "style-image" %>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-xs-12 text-center">
          <% if @user == current_user %>
            <div class="row text-center">
              <%= link_to 'Style新規登録', new_style_path, class: "botton-date bottom-box d btn btn-danger" %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>

    <% if @user == current_user %>
    <!-- myいいね一覧 -->
      <div class="col-xs-12 style-main-visual" id="favorite-top">
        <div class="row">
          <div class="col-xs-12 text-center">
            <h2 class="main-tex"><strong>お気に入り Styles</strong></h2>
          </div>
        </div>
        <div class="row">
          <div class="my-styles-user">
            <div class="col-xs-12">
              <% current_user.favorites_styles.each do |favorites| %>
                <div class="box box-efect">
                <%= link_to style_path(favorites.id) do %>
                  <%= attachment_image_tag favorites, :image, :fill, 200, 250, format: 'jpeg', class: "style-image" %>
                <% end %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/withdraw.html.erb
<div class="row main-back">
  <div class="col-xs-12 text-center bottom-set">
<h1>本当に退会しますか？</h1>
<p>退会すると、会員登録情報や<br>これまでの機能がご利用できなくなります。<br>退会する場合は、「退会する」をクリックしてください。</p>

<div class="actions">
	<%= link_to "退会する", user_path(@user.id), method: :delete, class: "btn btn-sm btn-primary" %>
    <%= link_to "退会しない", edit_user_path, class: "btn btn-sm btn-danger" %>
</div>
</div>
</div>