config/routes.rb
Rails.application.routes.draw do

devise_for :admins, controllers: { sessions: 'admins/sessions' }

devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}

  namespace :admins do
     resources :users, only: [:show, :index, :destroy]
     resources :jenres, only: [:index, :edit, :create, :update]
     resources :top_admin, only: [:index]
  end

  root 'homes#top'
  get 'homes/top'

  get 'users/passwords/:id', to:"users#passwords", as: :passwords
  patch '/users/passwords/:id' ,to: "users#pass_update"
  put   '/users/passwords/:id' ,to: "users#pass_update"
  get 'users/withdraw/:id' => 'users#withdraw', as: :withdraw
  resources :users, only: [:show, :edit, :update, :destroy] do
    post 'follow/:id' => 'relationships#follow', as: 'follow'
    post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end

  resources :styles, only: [:index, :show, :new, :edit, :create, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
  end

  resources :boards, only: [:show, :index, :create, :destroy] do
    resource :board_comments, only: [:create, :destroy]
  end

  resources :chats, only: [:create]
  resources :rooms, only: [:create, :show]

  resources :salons, only: [:create, :destroy, :new, :edit, :update]

  resources :contacts, only: [:create]

  get 'tags/:tag', to: 'styles#index', as: :tag

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # 登録メール機能
  after_create :send_welcome_mail

  # 論理削除
  acts_as_paranoid

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :salons, dependent: :destroy
  has_many :styles, dependent: :destroy
  has_many :boards, dependent: :destroy
  has_many :board_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorites_styles, through: :favorites, source: :style
  has_many :chats, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  has_many :rooms, through: :user_rooms

  attachment :profile_image

  validates :name, presence: true, length: 2..20
  # user名前２から20文字いない
  validates :kana_name, presence: true, length: 2..20
  validates :nickname, presence: true, length: 2..20
  validates :prefectures, presence: true, length: 2..5
  validates :body, length: {maximum: 100}
  # プロフィール文50文字いない
  validates :email, presence: true

  enum status: { 一般: 0, 美容師: 1 }


  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # フォロワー取得
  has_many :following_user, through: :follower, source: :followed
  # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower
  # 自分をフォローしている人

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end

  # ユーザ登録後にメールを送信する処理
  def send_welcome_mail
    UserMailer.user_welcome_mail(self).deliver
  end

  def self.search(search)
      where(['nickname LIKE ?', "%#{search}%"])
  end

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :authenticate_admin!

  layout 'admins'

  def show
  	@user = User.find(params[:id])
  end

  def index
  	if params[:search]
  	  @users = User.without_deleted.search(params[:search])
  	else
  	  @users = User.without_deleted
  	 end
  	@user_deletes = User.only_deleted
  end

  def destroy
  	@user = User.find(params[:id])
  	@user.destroy
  	flash[:notice] = "会員を削除しました"
  	redirect_to admins_users_path
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :kana_name, :nickname, :prefectures, :status, :email])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  layout 'styletops'

  def show
    @user = User.find(params[:id])
    @user_salons = @user.salons
    @user_styles = @user.styles
    # チャット機能
    @currentUserEntry = UserRoom.where(user_id: current_user.id)
    @userEntry = UserRoom.where(user_id: @user.id)

    # 自分のルーム一覧
    targetRoomIdList = UserRoom.select(:room_id).where(user_id: @user.id)
    @rooms = Room.where(id: targetRoomIdList)

    # サイドバー
    @jenres = Jenre.all
    @tags = ActsAsTaggableOn::Tag.all
    @boards_new = Board.limit(5).order("created_at desc")
    @styels_new = Style.limit(12).order("created_at desc")

    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isroom = true
            @roomid = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = UserRoom.new
      end
    end
  end

  def edit
    @user = User.find(params[:id])

    # サイドバー
    @jenres = Jenre.all
    @tags = ActsAsTaggableOn::Tag.all
    @boards_new = Board.limit(5).order("created_at desc")
    @styels_new = Style.limit(12).order("created_at desc")

    if current_user != @user
      redirect_back(fallback_location: root_path)
    end
  end

  def withdraw
    @user = User.find(params[:id])
  end

  def passwords
    @user = User.find(params[:id])
  end

  def pass_update
    @user = User.find(params[:id])
    if @user.update(password_params)
      flash[:notice] = "パスワードを変更しました"
      redirect_to root_path
    else
      render :passwords
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "会員情報を変更しました"
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private

    def user_params
      params.require(:user).permit(:name, :kana_name, :nickname, :prefectures, :status, :profile_image, :email, :body)
    end

    def password_params
      params.require(:user).permit(:password, :password_confirmation)
    end

end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/users/index.html.erb
<div class="row main-back">
  <div class="col-xs-12 text-center search-user">
    <h5><strong>User検索(ニックネーム)</strong></h5>
      <%= form_tag(admins_users_path, :method => "get") do %>
        <p>
          <%= text_field_tag :search, params[:search] %>
          <%= submit_tag "検索", :nickname => nil %>
        </p>
      <% end %>
  </div>
  <div class="col-xs-12 text-center admin-user-main">
    <h3><strong class="user-main-text">会員一覧</strong></h3><br>
    <div class="col-xs-2">
    </div>
    <div class="col-xs-7 admin-user-box">
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>氏名</th>
            <th>ニックネーム</th>
            <th>メールアドレス</th>
          </tr>
        </thead>

        <tbody class="admin-users">
        <% @users.each do |j| %>
          <tr>
            <td>
              <%= link_to admins_user_path(j.id) do %>
                <%= j.name %>
              <% end %>
            </td>
            <td>
              <%= j.nickname %>
            </td>
            <td>
              <%= j.email %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>

    <div class="col-xs-12 text-center admin-user-main">
    <h3><strong class="user-main-text">会員退会済一覧</strong></h3><br>
    <div class="col-xs-2">
    </div>
    <div class="col-xs-7 admin-user-box">
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>氏名</th>
            <th>ニックネーム</th>
            <th>メールアドレス</th>
          </tr>
        </thead>

        <tbody class="admin-users">
        <% @user_deletes.each do |j| %>
          <tr>
            <td>
                <%= j.name %>
            </td>
            <td>
              <%= j.nickname %>
            </td>
            <td>
              <%= j.email %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admins/users/show.html.erb
<div class="row main-back">
  <div class="col-xs-12 text-center admin-user-main back-black">
    <h2><strong>会員詳細画面</strong></h2><br>
    <div class="col-xs-1">
    </div>
    <div class="col-xs-10">

      <div class="form-group row admin-user-items">
        <label for="ID" class="col-sm-3 col-form-label text-right">会員ID</label>
        <div class="col-sm-9">
            <%= @user.id %>
        </div>
      </div>

      <div class="form-group row admin-user-items">
        <label for="name" class="col-sm-3 col-form-label text-right">氏名</label>
        <div class="col-sm-9">
  	      <%= @user.name %>
        </div>
      </div>

      <div class="form-group row admin-user-items">
        <label for="name" class="col-sm-3 col-form-label text-right">フリガナ</label>
        <div class="col-sm-9">
          <%= @user.kana_name %>
        </div>
      </div>

      <div class="form-group row admin-user-items">
        <label for="postcode" class="col-sm-3 col-form-label text-right">ニックネーム</label>
        <div class="col-sm-9">
          <%= @user.nickname %>
        </div>
      </div>

      <div class="form-group row admin-user-items">
        <label for="adress" class="col-sm-3 col-form-label text-right">都道府県</label>
        <div class="col-sm-9">
          <%= @user.prefectures %>
        </div>
      </div>

      <div class="form-group row admin-user-items">
        <label for="phone" class="col-sm-3 col-form-label text-right">情報</label>
        <div class="col-sm-9">
          <%= @user.status %>
        </div>
      </div>

      <div class="col-xs-12 text-right">
        <%= link_to "会員削除", admins_user_path(@user.id), method: :delete, class: "btn btn-sm btn-primary" %>
      </div>
　  </div>
  </div>
</div>