config/routes.rb
Rails.application.routes.draw do

devise_for :admins, controllers: { sessions: 'admins/sessions' }

devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}

  namespace :admins do
     resources :users, only: [:show, :index, :destroy]
     resources :jenres, only: [:index, :edit, :create, :update]
     resources :top_admin, only: [:index]
  end

  root 'homes#top'
  get 'homes/top'

  get 'users/passwords/:id', to:"users#passwords", as: :passwords
  patch '/users/passwords/:id' ,to: "users#pass_update"
  put   '/users/passwords/:id' ,to: "users#pass_update"
  get 'users/withdraw/:id' => 'users#withdraw', as: :withdraw
  resources :users, only: [:show, :edit, :update, :destroy] do
    post 'follow/:id' => 'relationships#follow', as: 'follow'
    post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end

  resources :styles, only: [:index, :show, :new, :edit, :create, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
  end

  resources :boards, only: [:show, :index, :create, :destroy] do
    resource :board_comments, only: [:create, :destroy]
  end

  resources :chats, only: [:create]
  resources :rooms, only: [:create, :show]

  resources :salons, only: [:create, :destroy, :new, :edit, :update]

  resources :contacts, only: [:create]

  get 'tags/:tag', to: 'styles#index', as: :tag

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/style.rb
class Style < ApplicationRecord

    acts_as_taggable

    attachment :image
    attachment :image_second
    attachment :image_third

    belongs_to :jenre
    belongs_to :user
    has_many :favorites, dependent: :destroy
	def favorited_by?(user)
       favorites.where(user_id: user.id).exists?
    end

    validates :name, presence: true, length: 2..20
    validates :content, presence: true, length: {maximum: 100}
    validates :price, length: {maximum: 10}
    validates :color_style, presence: true, length: {maximum: 20}
    validates :menu, presence: true, length: 2..25

    enum status: { MENS: 0, LADIES: 1 }

    def self.search(search)
       Style.joins(:user).where(['prefectures LIKE ? OR nickname LIKE ?', "%#{search}%", "%#{search}%"])
    end

end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :authenticate_user!, only:[:new, :edit, :create, :update, :destroy]

  layout 'styletops'

  def index
    @jenres = Jenre.all
    @tags = ActsAsTaggableOn::Tag.all
    @boards_new = Board.limit(5).order("created_at desc")
    @styels_new = Style.limit(12).order("created_at desc")

    # ソート
    @created_at = '投稿順▲'
    @created_at_num = 0

    if user_signed_in?
      @user = current_user.favorites_styles
      @user_favorites = @user.limit(5).order("created_at desc")
    end

    if params[:created_at] && params[:tag]
      # ソート機能(タグ)
      @created_at_num = params[:created_at].to_i
      @style_tag = Style.tagged_with(params[:tag])
      if @created_at_num == 2
        # タグ古い順
        @rank = Style.joins(:favorites).group("favorites.style_id").where(id: @style_tag).order('count(style_id) desc').limit(5)
        @style_tag = Style.tagged_with(params[:tag])
        @styles = @style_tag.order("created_at asc").all.page(params[:page]).per(30)
        @created_at = '投稿順▼'
        @created_at_num = 3
      else
        # タグ新着順
        @rank = Style.joins(:favorites).group("favorites.style_id").where(id: @style_tag).order('count(style_id) desc').limit(5)
        @style_tag = Style.tagged_with(params[:tag])
        @styles = @style_tag.order("created_at desc").all.page(params[:page]).per(30)
        @created_at = '新着順▲'
        @created_at_num = 2
      end
    elsif params[:tag]
    # タグ検索
      @created_at_num = 2
      @style_tag = Style.tagged_with(params[:tag])
      @styles = @style_tag.order("created_at desc").all.page(params[:page]).per(30)
      @rank = Style.joins(:favorites).group("favorites.style_id").where(id: @style_tag).order('count(style_id) desc').limit(5)
    elsif params[:status] == "MENS"
    # メンズ検索
      @created_at_num = 4
      @styles = Style.where(status: "MENS").order("created_at desc").all.page(params[:page]).per(30)
      @rank = Style.joins(:favorites).group("favorites.style_id").where(status: "MENS").order('count(style_id) desc').limit(5)
    elsif params[:status] == "LADIES"
    # レディース検索
      @created_at_num = 6
      @styles = Style.where(status: "LADIES").order("created_at desc").all.page(params[:page]).per(30)
      @rank = Style.joins(:favorites).group("favorites.style_id").where(status: "LADIES").order('count(style_id) desc').limit(5)
    elsif params[:created_at] && params[:jenre_id]
    # ソート機能(ジャンル)
      @created_at_num = params[:created_at].to_i
      @jenre = Jenre.find(params[:jenre_id])
      if @created_at_num == 8
        # ジャンル古い順
        @styles = @jenre.styles.order("created_at asc").all.page(params[:page]).per(30)
        @rank = Style.joins(:favorites).group("favorites.style_id").where(jenre_id: @jenre.id).order('count(style_id) desc').limit(5)
        @created_at = '投稿順▼'
        @created_at_num = 9
      else
        # レディース新着順
        @styles = @jenre.styles.order("created_at desc").all.page(params[:page]).per(30)
        @rank = Style.joins(:favorites).group("favorites.style_id").where(jenre_id: @jenre.id).order('count(style_id) desc').limit(5)
        @created_at = '新着順▲'
        @created_at_num = 8
      end
    elsif params[:jenre_id]
    # ジャンル検索
      @created_at_num = 8
      @jenre = Jenre.find(params[:jenre_id])
      @styles = @jenre.styles.order("created_at desc").all.page(params[:page]).per(30)
      @rank = Style.joins(:favorites).group("favorites.style_id").where(jenre_id: @jenre.id).order('count(style_id) desc').limit(5)
    elsif params[:search]
    # スタイリスト名 &　都道府県検索
      @styles_search = Style.search(params[:search])
      @styles = @styles_search.order("created_at desc").all.page(params[:page]).per(30)
      @rank = Style.joins(:favorites).group("favorites.style_id").where(id: @styles_search).order('count(style_id) desc').limit(5)
    elsif params[:created_at]
    # ソート機能
      @created_at_num = params[:created_at].to_i

      if @created_at_num == 0
        @rank = Style.find(Favorite.group(:style_id).order('count(style_id) desc').limit(5).pluck(:style_id))
        @styles = Style.order("created_at asc").all.page(params[:page]).per(30)
        @created_at = '新着順▲'
        @created_at_num = 1
      elsif @created_at_num == 4
        # メンズ古い順
        @rank = Style.joins(:favorites).group("favorites.style_id").where(status: "MENS").order('count(style_id) desc').limit(5)
        @styles = Style.where(status: "MENS").order("created_at asc").all.page(params[:page]).per(30)
        @created_at = '投稿順▼'
        @created_at_num = 5
      elsif @created_at_num == 5
        # メンズ新着順
        @rank = Style.joins(:favorites).group("favorites.style_id").where(status: "MENS").order('count(style_id) desc').limit(5)
        @styles = Style.where(status: "MENS").order("created_at desc").all.page(params[:page]).per(30)
        @created_at = '新着順▲'
        @created_at_num = 4
      elsif @created_at_num == 6
        # レディース古い順
        @rank = Style.joins(:favorites).group("favorites.style_id").where(status: "LADIES").order('count(style_id) desc').limit(5)
        @styles = Style.where(status: "LADIES").order("created_at asc").all.page(params[:page]).per(30)
        @created_at = '投稿順▼'
        @created_at_num = 7
      elsif @created_at_num == 7
        # レディース新着順
        @rank = Style.joins(:favorites).group("favorites.style_id").where(status: "LADIES").order('count(style_id) desc').limit(5)
        @styles = Style.where(status: "LADIES").order("created_at desc").all.page(params[:page]).per(30)
        @created_at = '新着順▲'
        @created_at_num = 6
      else
        @rank = Style.find(Favorite.group(:style_id).order('count(style_id) desc').limit(5).pluck(:style_id))
        @styles = Style.order("created_at desc").all.page(params[:page]).per(30)
        @created_at = '投稿順▼'
        @created_at_num = 0
      end
    else
      @styles = Style.order("created_at desc").all.page(params[:page]).per(30)
      @rank = Style.find(Favorite.group(:style_id).order('count(style_id) desc').limit(5).pluck(:style_id))
    end
    # 以前のデータ
    # if params[:tag]
    #   @styles = Style.tagged_with(params[:tag])
    #   @rank = Style.joins(:favorites).group("favorites.style_id").where(id: @styles).order('count(style_id) desc').limit(5)
    # elsif params[:status] == "MENS"
    #   @styles = Style.where(status: "MENS").order("RAND()").all
    #   @rank = Style.joins(:favorites).group("favorites.style_id").where(status: "MENS").order('count(style_id) desc').limit(5)
    # elsif params[:status] == "LADIES"
    #   @styles = Style.where(status: "LADIES").order("RAND()").all
    #   @rank = Style.joins(:favorites).group("favorites.style_id").where(status: "LADIES").order('count(style_id) desc').limit(5)
    # elsif params[:jenre_id]
    #   @jenre = Jenre.find(params[:jenre_id])
    #   @styles = @jenre.styles.order("RAND()").all
    #   @rank = Style.joins(:favorites).group("favorites.style_id").where(jenre_id: @jenre.id).order('count(style_id) desc').limit(5)
    # elsif params[:search]
    #   @styles = Style.search(params[:search])
    #   @rank = Style.joins(:favorites).group("favorites.style_id").where(id: @styles).order('count(style_id) desc').limit(5)
    # else
    #   @styles = Style.order("RAND()").all
    #   @rank = Style.find(Favorite.group(:style_id).order('count(style_id) desc').limit(5).pluck(:style_id))
    # end
  end

  def show
    @style = Style.find(params[:id])
    @user_styles = @style.user.styles
    @jenres = Jenre.all
    @tags = ActsAsTaggableOn::Tag.all
    @boards_new = Board.limit(5).order("created_at desc")
    @styels_new = Style.limit(12).order("created_at desc")
  end

  def new
    @style = Style.new
    @tags = ActsAsTaggableOn::Tag.all
    @jenres = Jenre.all
    @boards_new = Board.limit(5).order("created_at desc")
    @styels_new = Style.limit(12).order("created_at desc")
  end

  def edit
    @style = Style.find(params[:id])
    @tags = ActsAsTaggableOn::Tag.all
    @jenres = Jenre.all
    @boards_new = Board.limit(5).order("created_at desc")
    @styels_new = Style.limit(12).order("created_at desc")
    if @style.user_id != current_user.id
      redirect_back(fallback_location: root_path)
    end
  end

  def create
    @style = Style.new(style_params)
    @style.user_id = current_user.id
    if @style.save
      flash[:notice] = "スタイルを登録しました"
      redirect_to style_path(@style.id)
    else
      @tags = ActsAsTaggableOn::Tag.all
      render :new
    end
  end

  def update
    @style = Style.find(params[:id])
    if @style.update(style_params)
      flash[:notice] = "スタイルを更新しました"
      redirect_to style_path(@style.id)
    else
      @tags = ActsAsTaggableOn::Tag.all
      render :edit
    end
  end

  def destroy
      @style = Style.find(params[:id])
      @style.destroy
      redirect_to user_path(current_user.id)
  end

  private

    def style_params
      params.require(:style).permit(:name, :content, :price, :jenre_id, :user_id, :status, :menu, :color_style, :image, :image_second, :image_third, tag_list: [])
    end

end

app/helpers/styles_helper.rb
module StylesHelper
end

app/views/styles/edit.html.erb
<div class="row">
  <div class="col-xs-2 index-status">
    <%= render 'layouts/sidebar', jenres: @jenres, tags: @tags, boards_new: @boards_new, styels_new: @styels_new %>
  </div>

  <div class="col-xs-10">

    <div class="col-xs-12 text-center">
	    <h2 class="main-tex"><strong>Style 編集画面</strong></h2>
    </div>

    <div class="col-xs-12">
      <%= form_for @style do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        <div class="col-xs-12 text-center">
          <div class="col-xs-12">
            <p class="style-main"><strong>スタイルイメージ</strong></p>
          </div>
          <div class="col-xs-12">
            <div class="col-xs-4">
              <%= attachment_image_tag @style, :image, fallback: "no_image.jpg", id: :img_prev, class: "profile-image stylei" %><br>
              <%= f.attachment_field :image, class: "btn btn-danger image-tag_style", id: :user_img %>
              <p><strong>メインイメージ</strong></p>
            </div>
            <div class="col-xs-4">
              <%= attachment_image_tag @style, :image_second, fallback: "no_image.jpg", id: :img_two, class: "profile-image stylei" %><br>
              <%= f.attachment_field :image_second, class: "btn btn-danger image-tag_style", id: :style_two %>
              <p><strong>サブイメージ</strong></p>
            </div>
            <div class="col-xs-4">
              <%= attachment_image_tag @style, :image_third, fallback: "no_image.jpg", id: :img_three, class: "profile-image stylei" %><br>
              <%= f.attachment_field :image_third, class: "btn btn-danger image-tag_style", id: :style_three %>
              <p><strong>サブイメージ</strong></p>
            </div>
          </div>
        </div>
        <div class="col-xs-12 bottom-box">
          <div class="col-xs-6">
            <label class="col-sm-12 text-style">スタイル名</label>
            <div class="col-sm-12"><%= f.text_field :name, class: "my-edit" %></div>

            <label class="col-sm-12 text-style">性別</label>
            <div class="col-sm-12"><%= f.select :status, ['MENS', 'LADIES'] %></div>

            <label class="col-sm-12 text-style">スタイルPR</label>
            <div class="col-sm-12"><%= f.text_area :content, class: "my-edit" %></div>

            <label class="col-sm-12 text-style">ジャンル</label>
            <div class="col-sm-12"><%= f.select :jenre_id, Jenre.all.collect{ |j| [ j.name, j.id]} %></div>

            <label class="col-sm-12 text-style">メニュー</label>
            <div class="col-sm-12"><%= f.text_field :menu, class: "my-edit" %></div>

            <label class="col-sm-12 text-style">カラー</label>
            <label class="col-sm-12 text-style-mini">(カラー無しの場合は、「ノーカラー」とご記入ください)</label>
            <div class="col-sm-12"><%= f.text_field :color_style, class: "my-edit" %></div>

            <label class="col-sm-12 text-style">料金(税込)</label>
            <label class="col-sm-12 text-style-mini">(「¥」,「,」無し数字のみ、例、12000)</label>
            <div class="col-sm-12"><%= f.text_field :price, class: "my-edit" %></div>
          </div>

          <div class="col-xs-6">
            <label class="col-sm-12 text-style">タグ</label>
            <% @tags.each do |tag| %>
              <div class="tag-box">
                <%= f.check_box :tag_list, { multiple: true }, "#{tag.name}", nil %>
                <%= f.label " #{tag.name}(#{tag.taggings_count})", class: "label label-default lab" %>
              </div>
            <% end %>

            <div class="col-sm-12 text-right">
              <%= f.submit "編集完了", class: "btn btn-danger image-tag" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/styles/index.html.erb
<!-- スタイル一覧画面 -->
<div class="row">
  <div class="col-xs-2 index-status">
    <%= render 'layouts/sidebar', jenres: @jenres, tags: @tags, boards_new: @boards_new, styels_new: @styels_new %>
  </div>

  <!-- スタイル一覧 -->
  <div class="col-xs-10">
    <div class="col-xs-12 text-center">
      <h2 class="main-tex2"><strong>R a n k i n g</strong></h2>
    </div>
    <div class="col-xs-12 text-center">
      <div class="ranking-box center-block">
        <% @rank.each_with_index do |style, i| %>
          <div class="box-efect boxes text-center">
            <% if i == 0 %>
                <div class="crown-image1 center-block"><h3 class="crown-text"><%= i+1 %></h3></div>
              <% elsif i == 1 %>
                <div class="crown-image2 center-block"><h3 class="crown-text"><%= i+1 %></h3></div>
              <% elsif i == 2 %>
                <div class="crown-image3 center-block"><h3 class="crown-text"><%= i+1 %></h3></div>
              <% else %>
                <div class="crown-image center-block"><h3 class="crown-text"><%= i+1 %></h3></div>
            <% end %>
            <%= link_to style_path(style.id) do %>
              <%= attachment_image_tag style, :image, :fill, 150, 200, format: 'jpeg' %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-xs-12 text-center">
      <h2 class="main-tex2"><strong>S t y l e s</strong></h2>
        <div class="sort-tag text-right">
          <% if params[:tag] %>
            <%= link_to @created_at, tag_path(created_at: @created_at_num, tag_list: @style_tag.name), class: "sort-text" %>
          <% elsif params[:jenre_id] %>
            <%= link_to @created_at, styles_path(created_at: @created_at_num, jenre_id: @jenre), class: "sort-text" %>
          <% elsif params[:search] %>
          <% else %>
            <%= link_to @created_at, styles_path(created_at: @created_at_num), class: "sort-text" %>
          <% end %>
        </div>
    </div>
    <div class="my-styles2">
      <div class="col-xs-12 text-center">
        <div class="styles-box center-block">
        <% @styles.each do |style| %>
            <div class="box-efect">
              <%= link_to style_path(style.id) do %>
                <%= attachment_image_tag style, :image, :fill, 200, 250, format: 'jpeg', class: "style-image" %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-xs-12 text-right">
      <%= paginate @styles %><br>
      <%= page_entries_info @styles %>
    </div>

    <div class="col-xs-12 text-center">
      <div class="center-block favorite-box">
      <h5 class="favorite-style"><strong>最近お気に入り登録したヘアスタイル</strong></h5>
      </div>
    </div>
    <div class="col-xs-12 text-center">
      <% if user_signed_in? %>
        <% if @user.size == 0 %>
          まだお気に入り登録されていません
        <% else %>
          <div class="ranking-box center-block">
            <% @user_favorites.each do |favorite| %>
              <div class="box-efect boxes text-center">
                <%= link_to style_path(favorite.id) do %>
                  <%= attachment_image_tag favorite, :image, :fill, 150, 200, format: 'jpeg' %>
                <% end %>
              </div>
            <% end %>
          </div>
          <div class="col-xs-12 text-right bottom-field">
            <%= link_to '>> お気に入り一覧へ', user_path(current_user, anchor: "favorite-top"), class: "favorite-list-text" %>
          </div>
        <% end %>
      <% else %>
        登録されていません
      <% end %>
    </div>

  </div>

</div>

app/views/styles/new.html.erb
<div class="row">

  <div class="col-xs-2 index-status">
    <%= render 'layouts/sidebar', jenres: @jenres, tags: @tags, boards_new: @boards_new, styels_new: @styels_new %>
  </div>

  <div class="col-xs-10">
    <div class="col-xs-12 text-center">
      <h2 class="main-tex"><strong>Style 新規登録画面</strong></h2>
    </div>

    <%= form_for @style do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
        <div class="row">
          <div class="col-xs-12 text-center">
            <div class="col-xs-12">
              <p class="style-main"><strong>スタイルイメージ</strong></p>
            </div>
            <div class="row">
              <div class="col-xs-4">
                <%= attachment_image_tag @style, :image, fallback: "no_image.jpg", id: :img_prev, class: "profile-image stylei" %><br>
                <%= f.attachment_field :image, class: "btn btn-danger image-tag_style", id: :user_img %>
                <p><strong>メインイメージ</strong></p>
              </div>
              <div class="col-xs-4">
                <%= attachment_image_tag @style, :image_second, fallback: "no_image.jpg", id: :img_two, class: "profile-image stylei" %><br>
                <%= f.attachment_field :image_second, class: "btn btn-danger image-tag_style", id: :style_two %>
                <p><strong>サブイメージ</strong></p>
              </div>
              <div class="col-xs-4">
                <%= attachment_image_tag @style, :image_third, fallback: "no_image.jpg", id: :img_three, class: "profile-image stylei" %><br>
                <%= f.attachment_field :image_third, class: "btn btn-danger image-tag_style", id: :style_three %>
                <p><strong>サブイメージ</strong></p>
              </div>
            </div>
          </div>
        </div>
        <div class="row bottom-box">
          <div class="col-xs-6">
            <label class="col-sm-12 text-style">スタイル名</label>
            <div class="col-sm-12"><%= f.text_field :name, placeholder: "20文字以内", class: "my-edit" %></div>

            <label class="col-sm-12 text-style">性別</label>
            <div class="col-sm-12"><%= f.select :status, ['MENS', 'LADIES'] %></div>

            <label class="col-sm-12 text-style">スタイルPR</label>
            <div class="col-sm-12"><%= f.text_area :content, placeholder: "100文字以内", class: "my-edit" %></div>

            <label class="col-sm-12 text-style">ジャンル</label>
            <div class="col-sm-12"><%= f.select :jenre_id, Jenre.all.collect{ |j| [ j.name, j.id]} %></div>

            <label class="col-sm-12 text-style">メニュー</label>
            <div class="col-sm-12"><%= f.text_field :menu, placeholder: "カット・カラー：25文字以内", class: "my-edit" %></div>

            <label class="col-sm-12 text-style">カラー</label>
            <label class="col-sm-12 text-style-mini">(カラー無しの場合は、「ノーカラー」とご記入ください)</label>
            <div class="col-sm-12"><%= f.text_field :color_style, placeholder: "ノーカラー：20文字以内", class: "my-edit" %></div>

            <label class="col-sm-12 text-style">料金(税込)</label>
            <label class="col-sm-12 text-style-mini">(「¥」,「,」無し数字のみ、例、12000)</label>
            <div class="col-sm-12"><%= f.text_field :price, placeholder: "10000：10文字以内", class: "my-edit" %></div>
          </div>

          <div class="col-xs-6">
            <label class="col-sm-12 text-style">タグ</label>
            <div class="col-sm-12">
              <% @tags.each do |tag| %>
                <div class="tag-box">
                  <%= f.check_box :tag_list, { multiple: true }, "#{tag.name}", nil %>
                  <%= f.label " #{tag.name}(#{tag.taggings_count})", class: "label label-default" %>
                </div>
              <% end %>
            </div>

            <div class="col-sm-12 text-right">
              <%= f.submit "新規作成", class: "btn btn-danger image-tag" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/styles/show.html.erb
<!-- Style詳細ページ -->
<div class="row">
  <div class="col-xs-2 index-status">
    <%= render 'layouts/sidebar', jenres: @jenres, tags: @tags, boards_new: @boards_new, styels_new: @styels_new %>
  </div>


  <div class="col-xs-10">
    <div class="style-main-visual col-xs-12">
      <div class="col-xs-12 text-center">
        <h2 class="main-tex"><strong>Style Page</strong></h2>
      </div>

      <!-- styleイメージ javascript設定（imageList imageList__view imageList__thumbnail） -->
      <div class="col-xs-6 text-center imageList">
  	    <div class="col-sm-12 imageList__view">
  	      <%= attachment_image_tag @style, :image, :fill, 350, 450, fallback: "no_image.jpg", class: "profile-image-white" %>
  	    </div>
        <div class="col-sm-12 my-top">
          <div class="col-sm-1">
          </div>
          <div class="col-sm-3 imageList__thumbnail selected">
            <%= attachment_image_tag @style, :image, :fill, 350, 450, fallback: "no_image.jpg", class: "profile-image-white" %>
          </div>
          <div class="col-sm-3 imageList__thumbnail">
            <%= attachment_image_tag @style, :image_second, :fill, 350, 450, fallback: "no_image.jpg", class: "profile-image-white" %>
          </div>
          <div class="col-sm-3 imageList__thumbnail">
            <%= attachment_image_tag @style, :image_third, :fill, 350, 450, fallback: "no_image.jpg", class: "profile-image-white imageList__thumbnail" %>
          </div>
        </div>
      </div>

      <div class="col-xs-6">

        <label class="col-sm-10 text-user my-style-main"><%= @style.name %></label>

        <% if user_signed_in? %>
          <label class="col-sm-10 text-user my-style-main text-right">
            <!-- いいね機能【非同期】 -->
            <div id="favorites_<%= @style.id %>">
              <%= render 'favorites/favorites', style: @style %>
            </div>
          </label>
        <% end %>

        <label class="col-sm-10 my-top text-styles"><%= @style.content %></label>

        <label class="col-sm-10 my-top"><%= @style.status %> | <%= @style.jenre.name %> | Color : <%= @style.color_style %></label>

        <label class="col-sm-10 my-top"><%= @style.menu %> | ¥ <%= @style.price %></label>

        <label class="col-sm-12 my-top">
    	    <%= raw(@style.tag_list.map { |t| link_to t, tag_path(t), class: "label label-default labb" }.join(' ')) %>
        </label>

        <% if @style.user == current_user %>
          <div class="col-sm-10 style-edit-box text-right">
            <%= link_to '編 集', edit_style_path(@style.id), class: "btn btn-danger style-edit" %>
            <%= link_to '削 除', style_path(@style.id), class: "btn btn-danger style-edit", method: :delete,"data-confirm" => "本当に削除しますか?" %>
          </div>
        <% end %>

        <label class="col-sm-10 text-style">Stylist</label>

        <div class="col-xs-12 botton-b">
          <div class="col-sm-3 text-center">
      	    <%= link_to user_path(@style.user.id) do %>
              <%= attachment_image_tag @style.user, :profile_image, :fill, 80, 120, fallback: "no_image.jpg", class: "profile-image-white style-profile" %>
            <% end %>
          </div>
          <label class="col-sm-8 my-top"><%= @style.user.nickname %><%= link_to 'StylistPage', user_path(@style.user.id), class: "btn-sm btn-danger image-tag stylistb" %></label>

          <label class="col-sm-8 my-top style-userb"><%= @style.user.body %></label>

        </div>

        <!-- myサロン一覧 -->
        <% @style.user.salons.each do |f| %>
          <div class="col-sm-12 text-styles botton-b">
            <label class="col-sm-8 my-top style-userb"><%= f.salon_name %></label>
            <label class="col-sm-8 my-top style-userb"><%= f.salon_address %></label>
            <label class="col-sm-8 my-top style-userb"><%= f.salon_phone %></label>
            <%= attachment_image_tag f, :salon_image, :fill, 120, 100, fallback: "no_image.jpg", class: "syadow" %>
          </div>
        <% end %>

      </div>
    </div>

    <!-- myスタイル一覧 -->
    <div class="col-xs-12 style-main-visual-mystyle">

      <div class="col-xs-12 text-center">
        <h2 class="main-tex"><strong><%= @style.user.nickname %> styles</strong></h2>
      </div>
      <div class="row">
        <div class="my-styles">
          <div class="col-xs-12">
            <% @user_styles.each do |f| %>
              <div class="box box-efect">
                <%= link_to style_path(f.id) do %>
                  <%= attachment_image_tag f, :image, :fill, 200, 250, format: 'jpeg', class: "style-image" %>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>